# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory to /app
WORKDIR /app

# Copy React frontend files to the container
COPY . /app

# Install React dependencies
RUN npm install
