version: '3'

services:
  backend:
    build:
      context: ./news_aggregator_be
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=mydatabase
      - DB_USERNAME=root
      - DB_PASSWORD=mysecretpassword
    depends_on:
      - db

  frontend:
    build:
      context: ./news_aggregator_fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_ROOT_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
